config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :stories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/story.rb
class Story < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-color: #3a0ca3">
    <%= yield %>
  </body>
</html>

app/views/stories/index.html.erb
<h1>Stories</h1>

<ul>
  <% @stories.each do |story| %>
    <li><%= link_to(story.title, story_path(story)) %></li>
  <% end %>
</ul>

app/views/stories/show.html.erb
<div class="row mt-5 p-3 ">
  <div class="container col-md-6 bg-white rounded p-4">
    <h1 class="text-center pb-3 px-3 fs-1 font-monospace"><%= @story.title %></h1>
    <div class="d-flex gap-3">
    <p class="w-50 text-justify ps-1 fw-semibold"><%= @story.content %></p>
     <%= image_tag(@story.image, class: "w-50 rounded") %>
     </div>
  </div>
</div>